services:
  coordinator:
    image: digitalcredentials/workflow-coordinator:0.1.0
    environment:
      - ENABLE_STATUS_SERVICE=false
      - PUBLIC_EXCHANGE_HOST=http://localhost:3000/api 
      - TENANT_TOKEN_LEF_TEST=UNPROTECTED
    ports:
      - "4005:4005"
  signing:
    image: digitalcredentials/signing-service:0.2.0
    environment:
      - TENANT_SEED_LEF_TEST=z1AeiPT496wWmo9BG2QYXeTusgFSZPNG3T9wNeTtjrQ3rCB
  transactions:
    image: digitalcredentials/transaction-service:0.1.0
  payload:
    build: 
      context: .
      dockerfile: Dockerfile.local
    container_name: "ad-payload"
    depends_on: 
      - coordinator
      # - redis
      # - mongo
    environment:
      - COORDINATOR_URL=${COORDINATOR_URL}
      - REDIS_URL=${REDIS_URL}
      - REDIS_PORT=${REDIS_PORT}
      - REDIS_PASSWORD=${REDIS_PASSWORD}
      - MONGODB_URI=${MONGODB_URI}
      - PAYLOAD_SECRET=${PAYLOAD_SECRET}
      - TENANT_NAME=${TENANT_NAME}
      - SMTP_HOST=${SMTP_HOST}
      - SMTP_USER=${SMTP_USER}
      - SMTP_PASS=${SMTP_PASS}
      - EMAIL_FROM=${EMAIL_FROM}
      - CLAIM_PAGE_URL=${CLAIM_PAGE_URL}
      - PAYLOAD_PUBLIC_SERVER_URL=${PAYLOAD_PUBLIC_SERVER_URL}
    ports:
      - "3000:3000"
    volumes:
      - ./src:/home/node/app/src
  claim-page:
    image: digitalcredentials/admin-dashboard-claim-page:0.1.0
    container_name: "ad-claim-page"
    depends_on: 
      - payload
    ports:
      - "8080:8080"
  # redis:
  #   image: redis:alpine
  #   container_name: ad-redis
  #   environment:
  #     - ALLOW_EMPTY_PASSWORD=${ALLOW_EMPTY_PASSWORD:-yes}
  #   ports:
  #     - "6379:6379"
  # mongo:
  #   image: mongo
  #   environment:
  #     MONGO_INITDB_ROOT_USERNAME: root
  #     MONGO_INITDB_ROOT_PASSWORD: example
volumes:
  transactions:
