version: '3.5'
services:
  coordinator:
    image: digitalcredentials/workflow-coordinator:test
    env_file:
      - ./.coordinator.env
    ports:
      - "4005:4005"
  signing:
    image: digitalcredentials/signing-service:test
  status:
    image: digitalcredentials/status-service:test
    env_file:
      - ./.status-service.env
  transactions:
    image: digitalcredentials/transaction-service:test
