version: '3.5'
services:
  coordinator:
    image: digitalcredentials/workflow-coordinator:test
    environment:
      - PUBLIC_EXCHANGE_HOST=http://192.168.68.60:4005
    ports:
      - "4005:4005"
  signing:
    image: digitalcredentials/signing-service:test
  transactions:
    image: digitalcredentials/transaction-service:test
